// Generated by sketch (mm: 1.3) from blink.ino -- do not edit by hand.
import mm.sketch;
using namespace mm::sketch;
void setup();
void loop();
// blink.ino (displaced by 6 lines)
void setup() {
    pinMode(LED_BUILTIN, OUTPUT);
    Serial.begin(115200);
    Serial.println("blink");
}

void loop() {
    ledOn();
    delay(500);
    ledOff();
    delay(500);
}
int main() { return mm::sketch::run(&setup, &loop); }
