#!/bin/sh
# Run flash.sh through the project's shell tool.

MM_BUILD="out"
echo "Flash application"
echo

if [ ! -x "${MM_BUILD}/bin/shell" ]; then
    exec sh flash.sh "$@"
fi

cmd="sh flash.sh"
for arg in "$@"; do
    cmd="$cmd '$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")'"
done

${MM_BUILD}/bin/shell "$cmd"
