// Generated by sketch (mm: 1.3) -- do not edit by hand.
//
// A vendored library includes Printable.h because its own
// toolchain ships one. Everything it declares is in Sketch.h
// here, which is beside this file and generated with it.
#pragma once

#include "Sketch.h"
