// Generated by sketch (mm: 1.3) -- do not edit by hand.
//
// The compatibility header a sketch toolchain supplies to every
// sketch, and that a vendored library includes by name,
// unconditionally, because its own toolchain provides one.
// modules.cpp does not, so sketch writes this one beside
// main.cpp, which includes it, and the build puts this directory
// on the include path. The names a library includes by reach it
// through the forwarding headers written beside it. Names below
// come from mm.sketch, <cstdint>, and the compatibility
// environment.
#pragma once

#include <cstddef>
#include <cstdint>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>

import mm.sketch;

using namespace mm::sketch;

// <cstdint> guarantees these names in namespace std and
// leaves the global ones unspecified. A vendored library
// writing unqualified uint8_t relies on a compiler rather
// than on the language without these.
using std::int8_t;    using std::uint8_t;
using std::int16_t;   using std::uint16_t;
using std::int32_t;   using std::uint32_t;
using std::int64_t;   using std::uint64_t;
using std::size_t;    using std::ptrdiff_t;

// The C allocator and the string routines, which a sketch
// library reaches through this header rather than by naming
// <stdlib.h> or <string.h> itself.
using std::malloc;    using std::calloc;
using std::realloc;   using std::free;
using std::memcpy;    using std::memmove;
using std::memset;    using std::memcmp;
using std::strlen;    using std::strcmp;
using std::strncmp;   using std::strcpy;
using std::strncpy;   using std::strcat;
using std::strncat;   using std::strstr;
using std::strchr;    using std::strrchr;
using std::strtok;
using std::sprintf;   using std::snprintf;
using std::vsnprintf; using std::sscanf;
using std::atoi;      using std::atol;
using std::atof;      using std::strtol;
using std::strtoul;   using std::strtod;

// Flash-string spellings. docs/modules-sketch.mdy declines the
// behaviour, not the spelling: placement is the linker's
// business here, so each of these is inert.
// The word(...) spelling, which is a macro upstream because it
// has to coexist with the type of the same name: a function-like
// macro expands only where a call follows, so word x still
// declares a variable and word(h, l) still builds a value.
#define word(...) makeWord(__VA_ARGS__)

#define F(string_literal) (string_literal)
#define PSTR(string_literal) (string_literal)
#define PROGMEM

// The floating-point spellings <cmath> defines as macros, which
// a sketch writes without including it.
using std::isnan;
using std::isinf;
#ifndef NAN
#define NAN (__builtin_nanf(""))
#endif
#ifndef INFINITY
#define INFINITY (__builtin_inff())
#endif

// The AVR flash readers. Nothing was placed in a separate
// address space, so each one reads the object it is given the
// address of. _near and _far are the same read here.
inline std::uint8_t pgm_read_byte(const void* address) {
    return *static_cast<const std::uint8_t*>(address);
}
inline std::uint16_t pgm_read_word(const void* address) {
    return *static_cast<const std::uint16_t*>(address);
}
inline std::uint32_t pgm_read_dword(const void* address) {
    return *static_cast<const std::uint32_t*>(address);
}
inline float pgm_read_float(const void* address) {
    return *static_cast<const float*>(address);
}
inline void* pgm_read_ptr(const void* address) {
    return *static_cast<void* const*>(address);
}
inline std::uint8_t pgm_read_byte_near(const void* a) { return pgm_read_byte(a); }
inline std::uint8_t pgm_read_byte_far(const void* a) { return pgm_read_byte(a); }
inline std::uint16_t pgm_read_word_near(const void* a) { return pgm_read_word(a); }
inline std::uint16_t pgm_read_word_far(const void* a) { return pgm_read_word(a); }
inline std::uint32_t pgm_read_dword_near(const void* a) { return pgm_read_dword(a); }
inline std::uint32_t pgm_read_dword_far(const void* a) { return pgm_read_dword(a); }
inline float pgm_read_float_near(const void* a) { return pgm_read_float(a); }
inline float pgm_read_float_far(const void* a) { return pgm_read_float(a); }
inline void* pgm_read_ptr_near(const void* a) { return pgm_read_ptr(a); }
inline void* pgm_read_ptr_far(const void* a) { return pgm_read_ptr(a); }

// The flash counterparts of the string routines, which read
// from the same memory for the same reason.
inline void* memcpy_P(void* d, const void* s, std::size_t n) { return std::memcpy(d, s, n); }
inline char* strcpy_P(char* d, const char* s) { return std::strcpy(d, s); }
inline std::size_t strlen_P(const char* s) { return std::strlen(s); }
inline int strcmp_P(const char* a, const char* b) { return std::strcmp(a, b); }

// Analog channel names, numbered in declaration order. A board's
// real mapping belongs to mm.mcu; until it is asked, a sketch
// naming a channel the board lacks fails when it reads it
// rather than when it names it.
inline constexpr unsigned int A0 = 0;
inline constexpr unsigned int A1 = 1;
inline constexpr unsigned int A2 = 2;
inline constexpr unsigned int A3 = 3;
inline constexpr unsigned int A4 = 4;
inline constexpr unsigned int A5 = 5;
inline constexpr unsigned int A6 = 6;
inline constexpr unsigned int A7 = 7;

// Mathematical constants, spelled as a sketch spells them.
// docs/modules-sketch.mdy exports the trigonometry; these are
// the values it takes, at the precision a double can hold.
inline constexpr double PI = 3.1415926535897932384626433832795;
inline constexpr double HALF_PI = 1.5707963267948966192313216916398;
inline constexpr double TWO_PI = 6.283185307179586476925286766559;
inline constexpr double EULER = 2.718281828459045235360287471352;
inline constexpr double DEG_TO_RAD = 0.017453292519943295769236907684886;
inline constexpr double RAD_TO_DEG = 57.295779513082320876798154814105;

// The foreign spelling of dispatch, which is what a sketch
// calls to let handlers run inside a wait of its own.
inline void yield() { dispatch(); }

// Bit patterns one to eight digits wide, as AVR's binary.h
// spells them. Constants rather than macros: each has a type,
// a scope, and a value the compiler can see.
inline constexpr unsigned int B0 = 0, B1 = 1;
inline constexpr unsigned int B00 = 0, B01 = 1, B10 = 2, B11 = 3;
inline constexpr unsigned int B000 = 0, B001 = 1, B010 = 2, B011 = 3,
    B100 = 4, B101 = 5, B110 = 6, B111 = 7;
inline constexpr unsigned int B0000 = 0, B0001 = 1, B0010 = 2, B0011 = 3,
    B0100 = 4, B0101 = 5, B0110 = 6, B0111 = 7,
    B1000 = 8, B1001 = 9, B1010 = 10, B1011 = 11,
    B1100 = 12, B1101 = 13, B1110 = 14, B1111 = 15;
inline constexpr unsigned int B00000 = 0, B00001 = 1, B00010 = 2, B00011 = 3,
    B00100 = 4, B00101 = 5, B00110 = 6, B00111 = 7,
    B01000 = 8, B01001 = 9, B01010 = 10, B01011 = 11,
    B01100 = 12, B01101 = 13, B01110 = 14, B01111 = 15,
    B10000 = 16, B10001 = 17, B10010 = 18, B10011 = 19,
    B10100 = 20, B10101 = 21, B10110 = 22, B10111 = 23,
    B11000 = 24, B11001 = 25, B11010 = 26, B11011 = 27,
    B11100 = 28, B11101 = 29, B11110 = 30, B11111 = 31;
inline constexpr unsigned int B000000 = 0, B000001 = 1, B000010 = 2, B000011 = 3,
    B000100 = 4, B000101 = 5, B000110 = 6, B000111 = 7,
    B001000 = 8, B001001 = 9, B001010 = 10, B001011 = 11,
    B001100 = 12, B001101 = 13, B001110 = 14, B001111 = 15,
    B010000 = 16, B010001 = 17, B010010 = 18, B010011 = 19,
    B010100 = 20, B010101 = 21, B010110 = 22, B010111 = 23,
    B011000 = 24, B011001 = 25, B011010 = 26, B011011 = 27,
    B011100 = 28, B011101 = 29, B011110 = 30, B011111 = 31,
    B100000 = 32, B100001 = 33, B100010 = 34, B100011 = 35,
    B100100 = 36, B100101 = 37, B100110 = 38, B100111 = 39,
    B101000 = 40, B101001 = 41, B101010 = 42, B101011 = 43,
    B101100 = 44, B101101 = 45, B101110 = 46, B101111 = 47,
    B110000 = 48, B110001 = 49, B110010 = 50, B110011 = 51,
    B110100 = 52, B110101 = 53, B110110 = 54, B110111 = 55,
    B111000 = 56, B111001 = 57, B111010 = 58, B111011 = 59,
    B111100 = 60, B111101 = 61, B111110 = 62, B111111 = 63;
inline constexpr unsigned int B0000000 = 0, B0000001 = 1, B0000010 = 2, B0000011 = 3,
    B0000100 = 4, B0000101 = 5, B0000110 = 6, B0000111 = 7,
    B0001000 = 8, B0001001 = 9, B0001010 = 10, B0001011 = 11,
    B0001100 = 12, B0001101 = 13, B0001110 = 14, B0001111 = 15,
    B0010000 = 16, B0010001 = 17, B0010010 = 18, B0010011 = 19,
    B0010100 = 20, B0010101 = 21, B0010110 = 22, B0010111 = 23,
    B0011000 = 24, B0011001 = 25, B0011010 = 26, B0011011 = 27,
    B0011100 = 28, B0011101 = 29, B0011110 = 30, B0011111 = 31,
    B0100000 = 32, B0100001 = 33, B0100010 = 34, B0100011 = 35,
    B0100100 = 36, B0100101 = 37, B0100110 = 38, B0100111 = 39,
    B0101000 = 40, B0101001 = 41, B0101010 = 42, B0101011 = 43,
    B0101100 = 44, B0101101 = 45, B0101110 = 46, B0101111 = 47,
    B0110000 = 48, B0110001 = 49, B0110010 = 50, B0110011 = 51,
    B0110100 = 52, B0110101 = 53, B0110110 = 54, B0110111 = 55,
    B0111000 = 56, B0111001 = 57, B0111010 = 58, B0111011 = 59,
    B0111100 = 60, B0111101 = 61, B0111110 = 62, B0111111 = 63,
    B1000000 = 64, B1000001 = 65, B1000010 = 66, B1000011 = 67,
    B1000100 = 68, B1000101 = 69, B1000110 = 70, B1000111 = 71,
    B1001000 = 72, B1001001 = 73, B1001010 = 74, B1001011 = 75,
    B1001100 = 76, B1001101 = 77, B1001110 = 78, B1001111 = 79,
    B1010000 = 80, B1010001 = 81, B1010010 = 82, B1010011 = 83,
    B1010100 = 84, B1010101 = 85, B1010110 = 86, B1010111 = 87,
    B1011000 = 88, B1011001 = 89, B1011010 = 90, B1011011 = 91,
    B1011100 = 92, B1011101 = 93, B1011110 = 94, B1011111 = 95,
    B1100000 = 96, B1100001 = 97, B1100010 = 98, B1100011 = 99,
    B1100100 = 100, B1100101 = 101, B1100110 = 102, B1100111 = 103,
    B1101000 = 104, B1101001 = 105, B1101010 = 106, B1101011 = 107,
    B1101100 = 108, B1101101 = 109, B1101110 = 110, B1101111 = 111,
    B1110000 = 112, B1110001 = 113, B1110010 = 114, B1110011 = 115,
    B1110100 = 116, B1110101 = 117, B1110110 = 118, B1110111 = 119,
    B1111000 = 120, B1111001 = 121, B1111010 = 122, B1111011 = 123,
    B1111100 = 124, B1111101 = 125, B1111110 = 126, B1111111 = 127;
inline constexpr unsigned int B00000000 = 0, B00000001 = 1, B00000010 = 2, B00000011 = 3,
    B00000100 = 4, B00000101 = 5, B00000110 = 6, B00000111 = 7,
    B00001000 = 8, B00001001 = 9, B00001010 = 10, B00001011 = 11,
    B00001100 = 12, B00001101 = 13, B00001110 = 14, B00001111 = 15,
    B00010000 = 16, B00010001 = 17, B00010010 = 18, B00010011 = 19,
    B00010100 = 20, B00010101 = 21, B00010110 = 22, B00010111 = 23,
    B00011000 = 24, B00011001 = 25, B00011010 = 26, B00011011 = 27,
    B00011100 = 28, B00011101 = 29, B00011110 = 30, B00011111 = 31,
    B00100000 = 32, B00100001 = 33, B00100010 = 34, B00100011 = 35,
    B00100100 = 36, B00100101 = 37, B00100110 = 38, B00100111 = 39,
    B00101000 = 40, B00101001 = 41, B00101010 = 42, B00101011 = 43,
    B00101100 = 44, B00101101 = 45, B00101110 = 46, B00101111 = 47,
    B00110000 = 48, B00110001 = 49, B00110010 = 50, B00110011 = 51,
    B00110100 = 52, B00110101 = 53, B00110110 = 54, B00110111 = 55,
    B00111000 = 56, B00111001 = 57, B00111010 = 58, B00111011 = 59,
    B00111100 = 60, B00111101 = 61, B00111110 = 62, B00111111 = 63,
    B01000000 = 64, B01000001 = 65, B01000010 = 66, B01000011 = 67,
    B01000100 = 68, B01000101 = 69, B01000110 = 70, B01000111 = 71,
    B01001000 = 72, B01001001 = 73, B01001010 = 74, B01001011 = 75,
    B01001100 = 76, B01001101 = 77, B01001110 = 78, B01001111 = 79,
    B01010000 = 80, B01010001 = 81, B01010010 = 82, B01010011 = 83,
    B01010100 = 84, B01010101 = 85, B01010110 = 86, B01010111 = 87,
    B01011000 = 88, B01011001 = 89, B01011010 = 90, B01011011 = 91,
    B01011100 = 92, B01011101 = 93, B01011110 = 94, B01011111 = 95,
    B01100000 = 96, B01100001 = 97, B01100010 = 98, B01100011 = 99,
    B01100100 = 100, B01100101 = 101, B01100110 = 102, B01100111 = 103,
    B01101000 = 104, B01101001 = 105, B01101010 = 106, B01101011 = 107,
    B01101100 = 108, B01101101 = 109, B01101110 = 110, B01101111 = 111,
    B01110000 = 112, B01110001 = 113, B01110010 = 114, B01110011 = 115,
    B01110100 = 116, B01110101 = 117, B01110110 = 118, B01110111 = 119,
    B01111000 = 120, B01111001 = 121, B01111010 = 122, B01111011 = 123,
    B01111100 = 124, B01111101 = 125, B01111110 = 126, B01111111 = 127,
    B10000000 = 128, B10000001 = 129, B10000010 = 130, B10000011 = 131,
    B10000100 = 132, B10000101 = 133, B10000110 = 134, B10000111 = 135,
    B10001000 = 136, B10001001 = 137, B10001010 = 138, B10001011 = 139,
    B10001100 = 140, B10001101 = 141, B10001110 = 142, B10001111 = 143,
    B10010000 = 144, B10010001 = 145, B10010010 = 146, B10010011 = 147,
    B10010100 = 148, B10010101 = 149, B10010110 = 150, B10010111 = 151,
    B10011000 = 152, B10011001 = 153, B10011010 = 154, B10011011 = 155,
    B10011100 = 156, B10011101 = 157, B10011110 = 158, B10011111 = 159,
    B10100000 = 160, B10100001 = 161, B10100010 = 162, B10100011 = 163,
    B10100100 = 164, B10100101 = 165, B10100110 = 166, B10100111 = 167,
    B10101000 = 168, B10101001 = 169, B10101010 = 170, B10101011 = 171,
    B10101100 = 172, B10101101 = 173, B10101110 = 174, B10101111 = 175,
    B10110000 = 176, B10110001 = 177, B10110010 = 178, B10110011 = 179,
    B10110100 = 180, B10110101 = 181, B10110110 = 182, B10110111 = 183,
    B10111000 = 184, B10111001 = 185, B10111010 = 186, B10111011 = 187,
    B10111100 = 188, B10111101 = 189, B10111110 = 190, B10111111 = 191,
    B11000000 = 192, B11000001 = 193, B11000010 = 194, B11000011 = 195,
    B11000100 = 196, B11000101 = 197, B11000110 = 198, B11000111 = 199,
    B11001000 = 200, B11001001 = 201, B11001010 = 202, B11001011 = 203,
    B11001100 = 204, B11001101 = 205, B11001110 = 206, B11001111 = 207,
    B11010000 = 208, B11010001 = 209, B11010010 = 210, B11010011 = 211,
    B11010100 = 212, B11010101 = 213, B11010110 = 214, B11010111 = 215,
    B11011000 = 216, B11011001 = 217, B11011010 = 218, B11011011 = 219,
    B11011100 = 220, B11011101 = 221, B11011110 = 222, B11011111 = 223,
    B11100000 = 224, B11100001 = 225, B11100010 = 226, B11100011 = 227,
    B11100100 = 228, B11100101 = 229, B11100110 = 230, B11100111 = 231,
    B11101000 = 232, B11101001 = 233, B11101010 = 234, B11101011 = 235,
    B11101100 = 236, B11101101 = 237, B11101110 = 238, B11101111 = 239,
    B11110000 = 240, B11110001 = 241, B11110010 = 242, B11110011 = 243,
    B11110100 = 244, B11110101 = 245, B11110110 = 246, B11110111 = 247,
    B11111000 = 248, B11111001 = 249, B11111010 = 250, B11111011 = 251,
    B11111100 = 252, B11111101 = 253, B11111110 = 254, B11111111 = 255;
