// Pawel Wodnicki (C) 2026
// 32bitmicro LLC (C) 2026
module;

#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cerrno>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>

module mm.ino;

namespace mm::ino {

bool is_absent_or_generated(const std::filesystem::path& file) {
    std::error_code ec;
    if (!std::filesystem::exists(file, ec) && !ec) return true;
    std::ifstream in(file);
    std::string first;
    std::getline(in, first);
    return first.rfind("// Generated by sketch", 0) == 0;
}

bool write_guarded(const std::filesystem::path& app_dir,
                   std::string_view target_filename,
                   std::string_view content,
                   std::string& error,
                   std::string_view temp_filename) {
    error.clear();
    // A name may sit one directory down, as avr/pgmspace.h does. That
    // directory is created when missing and opened without following a
    // symbolic link, so the write stays inside the application; the file and
    // its temporary are then named relative to it.
    std::string subdir;
    std::string target_str(target_filename);
    std::string temp_str = temp_filename.empty()
        ? (target_str + ".tmp")
        : std::string(temp_filename);
    if (const auto slash = target_str.find('/'); slash != std::string::npos) {
        subdir = target_str.substr(0, slash);
        target_str = target_str.substr(slash + 1);
        if (subdir.empty() || subdir == "." || subdir == ".." ||
            target_str.empty() || target_str.find('/') != std::string::npos) {
            error = "cannot write " + std::string(target_filename) +
                    ": only one plain directory level is allowed";
            return false;
        }
        if (temp_str.compare(0, subdir.size() + 1, subdir + "/") == 0)
            temp_str = temp_str.substr(subdir.size() + 1);
    }

    int dir_fd =
        ::open(app_dir.c_str(), O_RDONLY | O_DIRECTORY | O_CLOEXEC);
    if (dir_fd < 0) {
        error = "cannot open directory " + app_dir.string() + ": " +
                std::strerror(errno);
        return false;
    }
    if (!subdir.empty()) {
        if (::mkdirat(dir_fd, subdir.c_str(), 0777) < 0 && errno != EEXIST) {
            const int err = errno;
            ::close(dir_fd);
            error = "cannot create directory " + subdir + ": " + std::strerror(err);
            return false;
        }
        const int sub_fd = ::openat(dir_fd, subdir.c_str(),
                                    O_RDONLY | O_DIRECTORY | O_NOFOLLOW | O_CLOEXEC);
        const int err = errno;
        ::close(dir_fd);
        if (sub_fd < 0) {
            error = "cannot open directory " + subdir + ": " + std::strerror(err);
            return false;
        }
        dir_fd = sub_fd;
    }

    const int file_fd = ::openat(dir_fd, temp_str.c_str(),
                                 O_CREAT | O_EXCL | O_NOFOLLOW | O_WRONLY |
                                     O_CLOEXEC,
                                 0666);
    if (file_fd < 0) {
        const int err = errno;
        ::close(dir_fd);
        if (err == EEXIST) {
            error = "temporary file " + temp_str + " already exists";
        } else {
            error = "cannot create temporary file " + temp_str + ": " +
                    std::strerror(err);
        }
        return false;
    }

    const char* data = content.data();
    std::size_t remaining = content.size();
    while (remaining > 0) {
        const ssize_t written = ::write(file_fd, data, remaining);
        if (written < 0) {
            if (errno == EINTR) continue;
            const int err = errno;
            ::close(file_fd);
            ::unlinkat(dir_fd, temp_str.c_str(), 0);
            ::close(dir_fd);
            error = "write error on " + temp_str + ": " + std::strerror(err);
            return false;
        }
        data += written;
        remaining -= static_cast<std::size_t>(written);
    }

    if (::close(file_fd) < 0) {
        const int err = errno;
        ::unlinkat(dir_fd, temp_str.c_str(), 0);
        ::close(dir_fd);
        error = "close error on " + temp_str + ": " + std::strerror(err);
        return false;
    }

    if (::renameat(dir_fd, temp_str.c_str(), dir_fd, target_str.c_str()) < 0) {
        const int err = errno;
        ::unlinkat(dir_fd, temp_str.c_str(), 0);
        ::close(dir_fd);
        error = "cannot rename " + temp_str + " to " + target_str + ": " +
                std::strerror(err);
        return false;
    }

    ::close(dir_fd);
    return true;
}

}  // namespace mm::ino
