// Generated by sketch (mm: 1.3) from echo.ino -- do not edit by hand.
#include <string>
import mm.sketch;
using namespace mm::sketch;
void setup();
void loop();
// echo.ino (displaced by 7 lines)


void setup() {
    Serial.begin(115200);
}

void loop() {
    if (Serial.available() > 0) {
        std::string line = Serial.readStringUntil('\n');
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
        }
        Serial.println(line);
    }
}
int main() { return mm::sketch::run(&setup, &loop); }
